### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by westkite1201** [westkite1201/MovieAssemble#1]
- [ ] 네이버 영화 크롤링 우선구현 

- [ ] DB 선택 ( RDB OR NOSQL )

- [ ] 레이아웃 수정 ( 화면 설계서 대로 변경할것 )
